# Generated by Django 4.0.2 on 2022-02-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('Year', models.CharField(max_length=50)),
                ('CGPA', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('Content_you_have', models.CharField(max_length=50)),
            ],
        ),
    ]
