# Generated by Django 4.0.2 on 2022-02-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='instahandle',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='linked_in',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='upi_id',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='CGPA',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Content_you_have',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Year',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='github',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
